version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: log-monitor-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules